// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateBattleRes interface {
	createBattleRes()
}

type CreateCarRes interface {
	createCarRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreatePetRes interface {
	createPetRes()
}

type CreatePokemonRes interface {
	createPokemonRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DBHealthRes interface {
	dBHealthRes()
}

type DeleteBattleRes interface {
	deleteBattleRes()
}

type DeleteCarRes interface {
	deleteCarRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeletePetRes interface {
	deletePetRes()
}

type DeletePokemonRes interface {
	deletePokemonRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListBattleRes interface {
	listBattleRes()
}

type ListCarCarsRes interface {
	listCarCarsRes()
}

type ListCarRes interface {
	listCarRes()
}

type ListGroupRes interface {
	listGroupRes()
}

type ListGroupUsersRes interface {
	listGroupUsersRes()
}

type ListPetRes interface {
	listPetRes()
}

type ListPokemonFightsRes interface {
	listPokemonFightsRes()
}

type ListPokemonOpponentsRes interface {
	listPokemonOpponentsRes()
}

type ListPokemonRes interface {
	listPokemonRes()
}

type ListUserCarsRes interface {
	listUserCarsRes()
}

type ListUserGroupsRes interface {
	listUserGroupsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadBattleContenderRes interface {
	readBattleContenderRes()
}

type ReadBattleOponentRes interface {
	readBattleOponentRes()
}

type ReadBattleRes interface {
	readBattleRes()
}

type ReadCarRes interface {
	readCarRes()
}

type ReadGroupRes interface {
	readGroupRes()
}

type ReadPetRes interface {
	readPetRes()
}

type ReadPokemonRes interface {
	readPokemonRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateBattleRes interface {
	updateBattleRes()
}

type UpdateCarRes interface {
	updateCarRes()
}

type UpdateGroupRes interface {
	updateGroupRes()
}

type UpdatePetRes interface {
	updatePetRes()
}

type UpdatePokemonRes interface {
	updatePokemonRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
