// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoEntFiberPokeman/ent/battle"
	"GoEntFiberPokeman/ent/group"
	"GoEntFiberPokeman/ent/pokemon"
	"GoEntFiberPokeman/ent/schema"
	"GoEntFiberPokeman/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	battleFields := schema.Battle{}.Fields()
	_ = battleFields
	// battleDescCreatedAt is the schema descriptor for created_at field.
	battleDescCreatedAt := battleFields[2].Descriptor()
	// battle.DefaultCreatedAt holds the default value on creation for the created_at field.
	battle.DefaultCreatedAt = battleDescCreatedAt.Default.(func() time.Time)
	// battleDescUpdatedAt is the schema descriptor for updated_at field.
	battleDescUpdatedAt := battleFields[3].Descriptor()
	// battle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	battle.DefaultUpdatedAt = battleDescUpdatedAt.Default.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	pokemonFields := schema.Pokemon{}.Fields()
	_ = pokemonFields
	// pokemonDescName is the schema descriptor for name field.
	pokemonDescName := pokemonFields[1].Descriptor()
	// pokemon.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pokemon.NameValidator = pokemonDescName.Validators[0].(func(string) error)
	// pokemonDescDescription is the schema descriptor for description field.
	pokemonDescDescription := pokemonFields[2].Descriptor()
	// pokemon.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	pokemon.DescriptionValidator = pokemonDescDescription.Validators[0].(func(string) error)
	// pokemonDescCreatedAt is the schema descriptor for created_at field.
	pokemonDescCreatedAt := pokemonFields[5].Descriptor()
	// pokemon.DefaultCreatedAt holds the default value on creation for the created_at field.
	pokemon.DefaultCreatedAt = pokemonDescCreatedAt.Default.(func() time.Time)
	// pokemonDescUpdatedAt is the schema descriptor for updated_at field.
	pokemonDescUpdatedAt := pokemonFields[6].Descriptor()
	// pokemon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pokemon.DefaultUpdatedAt = pokemonDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
}
